name: flutter_courses
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  fluttertoast: ^8.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/Ismail_Elmogy_Quotes_App/images/quote.png
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-ExtraLight.ttf
          weight: 200

