name: flutter_courses
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.0
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_auth: ^4.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^6.0.2
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  google_sign_in: ^6.1.5
  hive_flutter: ^1.1.0
  http: ^1.0.0
  internet_connection_checker: ^0.0.1+4
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.0.15
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Ismail_Elmogy_Quotes_App/images/quote.png
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-ExtraLight.ttf
          weight: 200
