name: flutter_courses
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/Ismail_Elmogy_Quotes_App/images/quote.png
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/Ismail_Elmogy_Quotes_App/fonts/Tajawal-ExtraLight.ttf
          weight: 200

